/*
 * CalculatorService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CalculatorService.PCL;
using CalculatorService.PCL.Utilities;


namespace CalculatorService.PCL.Models
{
    public class ICalculatorSubtractInputMessage : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Subtract parameters;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("parameters")]
        public Models.Subtract Parameters 
        { 
            get 
            {
                return this.parameters; 
            } 
            set 
            {
                this.parameters = value;
                onPropertyChanged("Parameters");
            }
        }
    }
} 