/*
 * CalculatorService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using CalculatorService.PCL.Controllers;
using CalculatorService.PCL.Http.Client;
using CalculatorService.PCL.Utilities;

namespace CalculatorService.PCL
{
    public partial class CalculatorServiceClient
    {

        /// <summary>
        /// Singleton access to DefaultBindingICalculator controller
        /// </summary>
        public DefaultBindingICalculatorController DefaultBindingICalculator
        {
            get
            {
                return DefaultBindingICalculatorController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public CalculatorServiceClient() { }
        #endregion
    }
}